
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightNEGnonassocPOWADD DIV ENDL LPAREN MUL NUM POW RPAREN SUBline : expr ENDLline : error ENDLexpr : numberexpr2 : pownumexpr : LPAREN expr RPARENexpr2 : LPAREN expr2 RPARENexpr : SUB LPAREN expr RPAREN %prec NEGexpr2 : SUB LPAREN expr2 RPAREN %prec NEGexpr : expr ADD exprexpr2 : expr2 ADD expr2expr : expr SUB exprexpr2 : expr2 SUB expr2expr : expr MUL exprexpr2 : expr2 MUL expr2expr : expr POW expr2expr : expr DIV exprexpr2 : expr2 DIV expr2number : NUMnumber : SUB number %prec NEGpownum : NUMpownum : SUB pownum %prec NEG'
    
_lr_action_items = {'error':([0,],[3,]),'LPAREN':([0,5,6,9,10,11,12,13,17,24,25,30,31,32,33,36,],[5,5,17,5,5,5,24,5,5,24,36,24,24,24,24,24,]),'SUB':([0,2,4,5,6,7,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,],[6,10,-3,6,16,-18,6,6,6,25,6,10,16,6,-19,-9,-11,-13,-15,-4,25,35,-20,-16,-5,10,25,25,25,25,31,35,25,-21,-7,-10,-12,-14,-17,-6,31,-8,]),'NUM':([0,5,6,9,10,11,12,13,16,17,24,25,30,31,32,33,35,36,],[7,7,7,7,7,7,26,7,7,7,26,26,26,26,26,26,26,26,]),'$end':([1,8,14,],[0,-1,-2,]),'ENDL':([2,3,4,7,18,19,20,21,22,23,26,27,28,37,38,39,40,41,42,43,45,],[8,14,-3,-18,-19,-9,-11,-13,-15,-4,-20,-16,-5,-21,-7,-10,-12,-14,-17,-6,-8,]),'ADD':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[9,-3,-18,9,-19,-9,-11,-13,-15,-4,-20,-16,-5,9,30,-21,-7,-10,-12,-14,-17,-6,30,-8,]),'MUL':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[11,-3,-18,11,-19,11,11,-13,-15,-4,-20,-16,-5,11,32,-21,-7,32,32,-14,-17,-6,32,-8,]),'POW':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,37,38,39,40,41,42,43,45,],[12,-3,-18,12,-19,12,12,12,-15,-4,-20,12,-5,12,-21,-7,-10,-12,-14,-17,-6,-8,]),'DIV':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[13,-3,-18,13,-19,13,13,-13,-15,-4,-20,-16,-5,13,33,-21,-7,33,33,-14,-17,-6,33,-8,]),'RPAREN':([4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[-3,-18,28,-19,-9,-11,-13,-15,-4,-20,-16,-5,38,43,-21,-7,-10,-12,-14,-17,-6,45,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expr':([0,5,9,10,11,13,17,],[2,15,19,20,21,27,29,]),'number':([0,5,6,9,10,11,13,16,17,],[4,4,18,4,4,4,4,18,4,]),'expr2':([12,24,30,31,32,33,36,],[22,34,39,40,41,42,44,]),'pownum':([12,24,25,30,31,32,33,35,36,],[23,23,37,23,23,23,23,37,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expr ENDL','line',2,'p_line_expr','yaccrules.py',20),
  ('line -> error ENDL','line',2,'p_line_error','yaccrules.py',28),
  ('expr -> number','expr',1,'p_expr_number','yaccrules.py',41),
  ('expr2 -> pownum','expr2',1,'p_expr2_number','yaccrules.py',47),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','yaccrules.py',53),
  ('expr2 -> LPAREN expr2 RPAREN','expr2',3,'p_expr2_paren','yaccrules.py',57),
  ('expr -> SUB LPAREN expr RPAREN','expr',4,'p_expr_neg','yaccrules.py',61),
  ('expr2 -> SUB LPAREN expr2 RPAREN','expr2',4,'p_expr2_neg','yaccrules.py',67),
  ('expr -> expr ADD expr','expr',3,'p_expr_add','yaccrules.py',73),
  ('expr2 -> expr2 ADD expr2','expr2',3,'p_expr2_add','yaccrules.py',79),
  ('expr -> expr SUB expr','expr',3,'p_expr_sub','yaccrules.py',85),
  ('expr2 -> expr2 SUB expr2','expr2',3,'p_expr2_sub','yaccrules.py',91),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','yaccrules.py',97),
  ('expr2 -> expr2 MUL expr2','expr2',3,'p_expr2_mul','yaccrules.py',103),
  ('expr -> expr POW expr2','expr',3,'p_expr_pow','yaccrules.py',109),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','yaccrules.py',115),
  ('expr2 -> expr2 DIV expr2','expr2',3,'p_expr2_div','yaccrules.py',132),
  ('number -> NUM','number',1,'p_number_pos','yaccrules.py',148),
  ('number -> SUB number','number',2,'p_number_neg','yaccrules.py',152),
  ('pownum -> NUM','pownum',1,'p_pownum_pos','yaccrules.py',156),
  ('pownum -> SUB pownum','pownum',2,'p_pownum_neg','yaccrules.py',160),
]
